defaults:
  -
    scope:
      path: "assets"
    values:
      layout: "nothing"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


permalink: /:categories/:year/:month/:day/:title #:output_ext

title: "PureAsbestos.com"

collections:
  - fonts



markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # syntax_highlighter_opts:
    # default_lang: html
    # css_class: 'highlight'
    # span:
      # line_numbers: false
    # block:
      # formatter: Rouge::Formatters::HTMLLinewise
      # wrap: true
      # tag_name: span
      # class: line


