defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      layout: "post"


permalink: /:categories/:year/:month/:day/:title #:output_ext

title: "PureAsbestos.com"

collections:
  - icons